# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title

# Setup
title:               Ali GÖREN
tagline:             'Açık Kaynak, JavaScript, Python, .NET'
description:         ''
#url:                 ''
baseurl:             ''
paginate:            5
paginate_path:       "sayfa/:num"
excerpt_separator:   "<!--more-->"

settings:
  disqus_username: aligren
  avatar: /images/ali.jpg

# About/contact
author:
  name:              Ali GÖREN
  url:               https://github.com/aligoren
  email:             

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
